driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: opensuse-leap-42.1
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
 - name: package
   run_list:
   - recipe[chef_nrpe_test::default]
 - name: source
   run_list:
   - recipe[chef_nrpe_test::default]
   attributes:
     nrpe:
       install_method: 'source'
   excludes:
    - freebsd-10.3
    - freebsd-11.0
 - name: check
   run_list:
   - recipe[chef_nrpe_test::check]
